### ISSUE TITLE
Security 

### ISSUE THREAD

**Issue by 0xmemorygrinder** [CryptoOutcasts/Candy_Machine_Whitelist_Site#1]
Hello, I have a simple question for you, can the system be bypassed ? I saw that the verification is in the client side so anyone with basic js knowledge can bypass the if (notwhitelisted) no ?

Thanks

**Comment by Mitolius** [comment]
Hi,

There is three security issues at the moment:
1) Bot directly minting on the blockchain
2) If a user open more than 1 tab and spam the mint button, he can mint more than the reserve
3) The one you said

The only solution to do a true whitelist is to implement it in Rust Program.

Now you can use this code and only send the presale link at the date you plan to avoid people deeping in the code and see how to exploit it. But it not solve the 1) and 2) issues.

Bots can be spot and you can blacklist token they stole.
@CryptoOutcasts Do you have a solution for the second issues ? 

Thanks

**Comment by 0xmemorygrinder** [comment]
I was trying to implement this feature in the metaplex program but with my few knowledge in rust, it was difficult.
I don't want to set reserves so the second problem is not to me and I will post the link at the launch date.

Thanks for your answer ! Appreciate it, if you want to see my work on the program you can dm me on discord BabysitterDeClients#1445.

**Comment by Mitolius** [comment]
I send a friend request to DM

**Comment by CryptoOutcasts** [comment]
Anyone with js knowledge good enough if you give them long enough time can
simply crack your cm id and call it to mint so yes theres a security risk
as any offchain solution out there. Only an on chain solution is safe :)

**Comment by CryptoOutcasts** [comment]
let me reiterate my answer 
No one can bypass this website and mint with the button if theyre not whitelisted.
however. they can obtain the program id if they dig deep enough to find it and then create a backend script to just call your program id (candy machine) and mint through it without the need of the website. the only visible security risk in this website that i have seen is that there seems to be a glitch with reservers like Mitolius pointed out.

to reiterate:
1) If someone digs deep enough in the files of the website they can obtain your candy machine id and thus mint using their own version of the website / backend
2) spamming mint appears to make people mint over the reserve limit.

and thats basically it 
no one can bypass the disabled mint button because even if they did enable the button the api would still call the whitelisted members again :) , if its not in there then it will throw.
its like a double check 

PS: apologies for my short answer previously 👍

**Comment by 0xmemorygrinder** [comment]
Thanks for your answer but in my opinion the api security is can be bypassed if we remove the "if is whitelisted" on the client-side.

Thanks for your concern !
